--Lecture 데이터 생성
INSERT INTO lecture (created_date, last_modified_date, content, end_time, lecturer, place, remaining_number_seats, start_time, title, total_number_seats, lecture_id) VALUES (now(), now(), 'content1', DATEADD('HOUR', 14 , DATEADD('DAY', -3, now())), 'lecturer1', 'place1', 31, DATEADD('HOUR', 13 , DATEADD('DAY', -3, now())), 'title1', 31, 1);
INSERT INTO lecture (created_date, last_modified_date, content, end_time, lecturer, place, remaining_number_seats, start_time, title, total_number_seats, lecture_id) VALUES (now(), now(), 'content2', DATEADD('HOUR', 27 , DATEADD('DAY', -3, now())), 'lecturer2', 'place2', 32, DATEADD('HOUR', 26 , DATEADD('DAY', -4, now())), 'title2', 32, 2);
INSERT INTO lecture (created_date, last_modified_date, content, end_time, lecturer, place, remaining_number_seats, start_time, title, total_number_seats, lecture_id) VALUES (now(), now(), 'content3', DATEADD('HOUR', 40 , DATEADD('DAY', -3, now())), 'lecturer3', 'place3', 33, DATEADD('HOUR', 39 , DATEADD('DAY', -5, now())), 'title3', 33, 3);
INSERT INTO lecture (created_date, last_modified_date, content, end_time, lecturer, place, remaining_number_seats, start_time, title, total_number_seats, lecture_id) VALUES (now(), now(), 'content4', DATEADD('HOUR', 53 , DATEADD('DAY', -3, now())), 'lecturer4', 'place4', 34, DATEADD('HOUR', 52 , DATEADD('DAY', -6, now())), 'title4', 34, 4);
INSERT INTO lecture (created_date, last_modified_date, content, end_time, lecturer, place, remaining_number_seats, start_time, title, total_number_seats, lecture_id) VALUES (now(), now(), 'content5', DATEADD('HOUR', 66 , DATEADD('DAY', -3, now())), 'lecturer5', 'place5', 35, DATEADD('HOUR', 65 , DATEADD('DAY', -7, now())), 'title5', 35, 5);
INSERT INTO lecture (created_date, last_modified_date, content, end_time, lecturer, place, remaining_number_seats, start_time, title, total_number_seats, lecture_id) VALUES (now(), now(), 'content6', DATEADD('HOUR', 79 , DATEADD('DAY', -3, now())), 'lecturer6', 'place6', 36, DATEADD('HOUR', 78 , DATEADD('DAY', -8, now())), 'title6', 36, 6);
INSERT INTO lecture (created_date, last_modified_date, content, end_time, lecturer, place, remaining_number_seats, start_time, title, total_number_seats, lecture_id) VALUES (now(), now(), 'content7', DATEADD('HOUR', 92 , DATEADD('DAY', -3, now())), 'lecturer7', 'place7', 37, DATEADD('HOUR', 91 , DATEADD('DAY', -9, now())), 'title7', 37, 7);
INSERT INTO lecture (created_date, last_modified_date, content, end_time, lecturer, place, remaining_number_seats, start_time, title, total_number_seats, lecture_id) VALUES (now(), now(), 'content8', DATEADD('HOUR', 105 , DATEADD('DAY', -3, now())), 'lecturer8', 'place8', 38, DATEADD('HOUR', 104 , DATEADD('DAY', -10, now())), 'title8', 38, 8);
INSERT INTO lecture (created_date, last_modified_date, content, end_time, lecturer, place, remaining_number_seats, start_time, title, total_number_seats, lecture_id) VALUES (now(), now(), 'content9', DATEADD('HOUR', 118 , DATEADD('DAY', -3, now())), 'lecturer9', 'place9', 39, DATEADD('HOUR', 117 , DATEADD('DAY', -11, now())), 'title9', 39, 9);
INSERT INTO lecture (created_date, last_modified_date, content, end_time, lecturer, place, remaining_number_seats, start_time, title, total_number_seats, lecture_id) VALUES (now(), now(), 'content10', DATEADD('HOUR', 131 , DATEADD('DAY', -3, now())), 'lecturer10', 'place10', 40, DATEADD('HOUR', 130 , DATEADD('DAY', -12, now())), 'title10', 40, 10);
INSERT INTO lecture (created_date, last_modified_date, content, end_time, lecturer, place, remaining_number_seats, start_time, title, total_number_seats, lecture_id) VALUES (now(), now(), 'content11', DATEADD('HOUR', 144 , DATEADD('DAY', -3, now())), 'lecturer11', 'place11', 41, DATEADD('HOUR', 143 , DATEADD('DAY', -13, now())), 'title11', 41, 11);
INSERT INTO lecture (created_date, last_modified_date, content, end_time, lecturer, place, remaining_number_seats, start_time, title, total_number_seats, lecture_id) VALUES (now(), now(), 'content12', DATEADD('HOUR', 157 , DATEADD('DAY', -3, now())), 'lecturer12', 'place12', 42, DATEADD('HOUR', 156 , DATEADD('DAY', -14, now())), 'title12', 42, 12);
INSERT INTO lecture (created_date, last_modified_date, content, end_time, lecturer, place, remaining_number_seats, start_time, title, total_number_seats, lecture_id) VALUES (now(), now(), 'content13', DATEADD('HOUR', 170 , DATEADD('DAY', -3, now())), 'lecturer13', 'place13', 43, DATEADD('HOUR', 169 , DATEADD('DAY', -15, now())), 'title13', 43, 13);
INSERT INTO lecture (created_date, last_modified_date, content, end_time, lecturer, place, remaining_number_seats, start_time, title, total_number_seats, lecture_id) VALUES (now(), now(), 'content14', DATEADD('HOUR', 183 , DATEADD('DAY', -3, now())), 'lecturer14', 'place14', 44, DATEADD('HOUR', 182 , DATEADD('DAY', -16, now())), 'title14', 44, 14);
INSERT INTO lecture (created_date, last_modified_date, content, end_time, lecturer, place, remaining_number_seats, start_time, title, total_number_seats, lecture_id) VALUES (now(), now(), 'content15', DATEADD('HOUR', 196 , DATEADD('DAY', -3, now())), 'lecturer15', 'place15', 45, DATEADD('HOUR', 195 , DATEADD('DAY', -17, now())), 'title15', 45, 15);
INSERT INTO lecture (created_date, last_modified_date, content, end_time, lecturer, place, remaining_number_seats, start_time, title, total_number_seats, lecture_id) VALUES (now(), now(), 'content16', DATEADD('HOUR', 209 , DATEADD('DAY', -3, now())), 'lecturer16', 'place16', 46, DATEADD('HOUR', 208 , DATEADD('DAY', -18, now())), 'title16', 46, 16);
INSERT INTO lecture (created_date, last_modified_date, content, end_time, lecturer, place, remaining_number_seats, start_time, title, total_number_seats, lecture_id) VALUES (now(), now(), 'content17', DATEADD('HOUR', 222 , DATEADD('DAY', -3, now())), 'lecturer17', 'place17', 47, DATEADD('HOUR', 221 , DATEADD('DAY', -19, now())), 'title17', 47, 17);
INSERT INTO lecture (created_date, last_modified_date, content, end_time, lecturer, place, remaining_number_seats, start_time, title, total_number_seats, lecture_id) VALUES (now(), now(), 'content18', DATEADD('HOUR', 235 , DATEADD('DAY', -3, now())), 'lecturer18', 'place18', 48, DATEADD('HOUR', 234 , DATEADD('DAY', -20, now())), 'title18', 48, 18);
INSERT INTO lecture (created_date, last_modified_date, content, end_time, lecturer, place, remaining_number_seats, start_time, title, total_number_seats, lecture_id) VALUES (now(), now(), 'content19', DATEADD('HOUR', 248 , DATEADD('DAY', -3, now())), 'lecturer19', 'place19', 49, DATEADD('HOUR', 247 , DATEADD('DAY', -21, now())), 'title19', 49, 19);
INSERT INTO lecture (created_date, last_modified_date, content, end_time, lecturer, place, remaining_number_seats, start_time, title, total_number_seats, lecture_id) VALUES (now(), now(), 'content20', DATEADD('HOUR', 261 , DATEADD('DAY', -3, now())), 'lecturer20', 'place20', 50, DATEADD('HOUR', 260 , DATEADD('DAY', -22, now())), 'title20', 50, 20);


-- Member 데이터 생성
INSERT INTO member (created_date, last_modified_date, emp_no, name, member_id) VALUES (now(), now(), 'X0001', 'name1', 1);
INSERT INTO member (created_date, last_modified_date, emp_no, name, member_id) VALUES (now(), now(), 'X0002', 'name2', 2);
INSERT INTO member (created_date, last_modified_date, emp_no, name, member_id) VALUES (now(), now(), 'X0003', 'name3', 3);
INSERT INTO member (created_date, last_modified_date, emp_no, name, member_id) VALUES (now(), now(), 'X0004', 'name4', 4);
INSERT INTO member (created_date, last_modified_date, emp_no, name, member_id) VALUES (now(), now(), 'X0005', 'name5', 5);
INSERT INTO member (created_date, last_modified_date, emp_no, name, member_id) VALUES (now(), now(), 'X0006', 'name6', 6);
INSERT INTO member (created_date, last_modified_date, emp_no, name, member_id) VALUES (now(), now(), 'X0007', 'name7', 7);
INSERT INTO member (created_date, last_modified_date, emp_no, name, member_id) VALUES (now(), now(), 'X0008', 'name8', 8);
INSERT INTO member (created_date, last_modified_date, emp_no, name, member_id) VALUES (now(), now(), 'X0009', 'name9', 9);
INSERT INTO member (created_date, last_modified_date, emp_no, name, member_id) VALUES (now(), now(), 'X0010', 'name10', 10);
INSERT INTO member (created_date, last_modified_date, emp_no, name, member_id) VALUES (now(), now(), 'X0011', 'name11', 11);
INSERT INTO member (created_date, last_modified_date, emp_no, name, member_id) VALUES (now(), now(), 'X0012', 'name12', 12);
INSERT INTO member (created_date, last_modified_date, emp_no, name, member_id) VALUES (now(), now(), 'X0013', 'name13', 13);
INSERT INTO member (created_date, last_modified_date, emp_no, name, member_id) VALUES (now(), now(), 'X0014', 'name14', 14);
INSERT INTO member (created_date, last_modified_date, emp_no, name, member_id) VALUES (now(), now(), 'X0015', 'name15', 15);
INSERT INTO member (created_date, last_modified_date, emp_no, name, member_id) VALUES (now(), now(), 'X0016', 'name16', 16);
INSERT INTO member (created_date, last_modified_date, emp_no, name, member_id) VALUES (now(), now(), 'X0017', 'name17', 17);
INSERT INTO member (created_date, last_modified_date, emp_no, name, member_id) VALUES (now(), now(), 'X0018', 'name18', 18);
INSERT INTO member (created_date, last_modified_date, emp_no, name, member_id) VALUES (now(), now(), 'X0019', 'name19', 19);
INSERT INTO member (created_date, last_modified_date, emp_no, name, member_id) VALUES (now(), now(), 'X0020', 'name20', 20);
INSERT INTO member (created_date, last_modified_date, emp_no, name, member_id) VALUES (now(), now(), 'X0021', 'name21', 21);
INSERT INTO member (created_date, last_modified_date, emp_no, name, member_id) VALUES (now(), now(), 'X0022', 'name22', 22);
INSERT INTO member (created_date, last_modified_date, emp_no, name, member_id) VALUES (now(), now(), 'X0023', 'name23', 23);
INSERT INTO member (created_date, last_modified_date, emp_no, name, member_id) VALUES (now(), now(), 'X0024', 'name24', 24);
INSERT INTO member (created_date, last_modified_date, emp_no, name, member_id) VALUES (now(), now(), 'X0025', 'name25', 25);
INSERT INTO member (created_date, last_modified_date, emp_no, name, member_id) VALUES (now(), now(), 'X0026', 'name26', 26);
INSERT INTO member (created_date, last_modified_date, emp_no, name, member_id) VALUES (now(), now(), 'X0027', 'name27', 27);
INSERT INTO member (created_date, last_modified_date, emp_no, name, member_id) VALUES (now(), now(), 'X0028', 'name28', 28);
INSERT INTO member (created_date, last_modified_date, emp_no, name, member_id) VALUES (now(), now(), 'X0029', 'name29', 29);
INSERT INTO member (created_date, last_modified_date, emp_no, name, member_id) VALUES (now(), now(), 'X0030', 'name30', 30);
INSERT INTO member (created_date, last_modified_date, emp_no, name, member_id) VALUES (now(), now(), 'X0031', 'name31', 31);
INSERT INTO member (created_date, last_modified_date, emp_no, name, member_id) VALUES (now(), now(), 'X0032', 'name32', 32);
INSERT INTO member (created_date, last_modified_date, emp_no, name, member_id) VALUES (now(), now(), 'X0033', 'name33', 33);
INSERT INTO member (created_date, last_modified_date, emp_no, name, member_id) VALUES (now(), now(), 'X0034', 'name34', 34);
INSERT INTO member (created_date, last_modified_date, emp_no, name, member_id) VALUES (now(), now(), 'X0035', 'name35', 35);
INSERT INTO member (created_date, last_modified_date, emp_no, name, member_id) VALUES (now(), now(), 'X0036', 'name36', 36);
INSERT INTO member (created_date, last_modified_date, emp_no, name, member_id) VALUES (now(), now(), 'X0037', 'name37', 37);
INSERT INTO member (created_date, last_modified_date, emp_no, name, member_id) VALUES (now(), now(), 'X0038', 'name38', 38);
INSERT INTO member (created_date, last_modified_date, emp_no, name, member_id) VALUES (now(), now(), 'X0039', 'name39', 39);
INSERT INTO member (created_date, last_modified_date, emp_no, name, member_id) VALUES (now(), now(), 'X0040', 'name40', 40);


-- Reservation 데이터 생성
INSERT INTO reservation (created_date, last_modified_date, lecture_id, member_id, status, reservation_id) VALUES (now(), now(), 1, 1, 'COMPLETE', 1);
INSERT INTO reservation (created_date, last_modified_date, lecture_id, member_id, status, reservation_id) VALUES (now(), now(), 1, 2, 'COMPLETE', 2);
INSERT INTO reservation (created_date, last_modified_date, lecture_id, member_id, status, reservation_id) VALUES (now(), now(), 2, 3, 'COMPLETE', 3);
INSERT INTO reservation (created_date, last_modified_date, lecture_id, member_id, status, reservation_id) VALUES (now(), now(), 2, 4, 'COMPLETE', 4);
INSERT INTO reservation (created_date, last_modified_date, lecture_id, member_id, status, reservation_id) VALUES (now(), now(), 3, 5, 'COMPLETE', 5);
INSERT INTO reservation (created_date, last_modified_date, lecture_id, member_id, status, reservation_id) VALUES (now(), now(), 3, 6, 'COMPLETE', 6);
INSERT INTO reservation (created_date, last_modified_date, lecture_id, member_id, status, reservation_id) VALUES (now(), now(), 4, 7, 'COMPLETE', 7);
INSERT INTO reservation (created_date, last_modified_date, lecture_id, member_id, status, reservation_id) VALUES (now(), now(), 4, 8, 'COMPLETE', 8);
INSERT INTO reservation (created_date, last_modified_date, lecture_id, member_id, status, reservation_id) VALUES (now(), now(), 5, 9, 'COMPLETE', 9);
INSERT INTO reservation (created_date, last_modified_date, lecture_id, member_id, status, reservation_id) VALUES (now(), now(), 5, 10, 'COMPLETE', 10);
INSERT INTO reservation (created_date, last_modified_date, lecture_id, member_id, status, reservation_id) VALUES (now(), now(), 6, 11, 'COMPLETE', 11);
INSERT INTO reservation (created_date, last_modified_date, lecture_id, member_id, status, reservation_id) VALUES (now(), now(), 6, 12, 'COMPLETE', 12);
INSERT INTO reservation (created_date, last_modified_date, lecture_id, member_id, status, reservation_id) VALUES (now(), now(), 7, 13, 'COMPLETE', 13);
INSERT INTO reservation (created_date, last_modified_date, lecture_id, member_id, status, reservation_id) VALUES (now(), now(), 7, 14, 'COMPLETE', 14);
INSERT INTO reservation (created_date, last_modified_date, lecture_id, member_id, status, reservation_id) VALUES (now(), now(), 8, 15, 'COMPLETE', 15);
INSERT INTO reservation (created_date, last_modified_date, lecture_id, member_id, status, reservation_id) VALUES (now(), now(), 8, 16, 'COMPLETE', 16);
INSERT INTO reservation (created_date, last_modified_date, lecture_id, member_id, status, reservation_id) VALUES (now(), now(), 9, 17, 'COMPLETE', 17);
INSERT INTO reservation (created_date, last_modified_date, lecture_id, member_id, status, reservation_id) VALUES (now(), now(), 9, 18, 'COMPLETE', 18);
INSERT INTO reservation (created_date, last_modified_date, lecture_id, member_id, status, reservation_id) VALUES (now(), now(), 10, 19, 'COMPLETE', 19);
INSERT INTO reservation (created_date, last_modified_date, lecture_id, member_id, status, reservation_id) VALUES (now(), now(), 10, 20, 'COMPLETE', 20);
INSERT INTO reservation (created_date, last_modified_date, lecture_id, member_id, status, reservation_id) VALUES (now(), now(), 11, 21, 'COMPLETE', 21);
INSERT INTO reservation (created_date, last_modified_date, lecture_id, member_id, status, reservation_id) VALUES (now(), now(), 11, 22, 'COMPLETE', 22);
INSERT INTO reservation (created_date, last_modified_date, lecture_id, member_id, status, reservation_id) VALUES (now(), now(), 12, 23, 'COMPLETE', 23);
INSERT INTO reservation (created_date, last_modified_date, lecture_id, member_id, status, reservation_id) VALUES (now(), now(), 12, 24, 'COMPLETE', 24);
INSERT INTO reservation (created_date, last_modified_date, lecture_id, member_id, status, reservation_id) VALUES (now(), now(), 13, 25, 'COMPLETE', 25);
INSERT INTO reservation (created_date, last_modified_date, lecture_id, member_id, status, reservation_id) VALUES (now(), now(), 13, 26, 'COMPLETE', 26);
INSERT INTO reservation (created_date, last_modified_date, lecture_id, member_id, status, reservation_id) VALUES (now(), now(), 14, 27, 'COMPLETE', 27);
INSERT INTO reservation (created_date, last_modified_date, lecture_id, member_id, status, reservation_id) VALUES (now(), now(), 14, 28, 'COMPLETE', 28);
INSERT INTO reservation (created_date, last_modified_date, lecture_id, member_id, status, reservation_id) VALUES (now(), now(), 15, 29, 'COMPLETE', 29);
INSERT INTO reservation (created_date, last_modified_date, lecture_id, member_id, status, reservation_id) VALUES (now(), now(), 15, 30, 'COMPLETE', 30);
INSERT INTO reservation (created_date, last_modified_date, lecture_id, member_id, status, reservation_id) VALUES (now(), now(), 1, 6, 'COMPLETE', 31);
INSERT INTO reservation (created_date, last_modified_date, lecture_id, member_id, status, reservation_id) VALUES (now(), now(), 2, 7, 'COMPLETE', 32);
INSERT INTO reservation (created_date, last_modified_date, lecture_id, member_id, status, reservation_id) VALUES (now(), now(), 1, 7, 'COMPLETE', 33);
INSERT INTO reservation (created_date, last_modified_date, lecture_id, member_id, status, reservation_id) VALUES (now(), now(), 2, 8, 'COMPLETE', 34);
INSERT INTO reservation (created_date, last_modified_date, lecture_id, member_id, status, reservation_id) VALUES (now(), now(), 1, 8, 'COMPLETE', 35);
INSERT INTO reservation (created_date, last_modified_date, lecture_id, member_id, status, reservation_id) VALUES (now(), now(), 2, 9, 'COMPLETE', 36);
INSERT INTO reservation (created_date, last_modified_date, lecture_id, member_id, status, reservation_id) VALUES (now(), now(), 1, 9, 'COMPLETE', 37);
INSERT INTO reservation (created_date, last_modified_date, lecture_id, member_id, status, reservation_id) VALUES (now(), now(), 2, 10, 'COMPLETE', 38);
INSERT INTO reservation (created_date, last_modified_date, lecture_id, member_id, status, reservation_id) VALUES (now(), now(), 1, 10, 'COMPLETE', 39);
INSERT INTO reservation (created_date, last_modified_date, lecture_id, member_id, status, reservation_id) VALUES (now(), now(), 2, 11, 'COMPLETE', 40);
INSERT INTO reservation (created_date, last_modified_date, lecture_id, member_id, status, reservation_id) VALUES (now(), now(), 3, 11, 'COMPLETE', 41);
INSERT INTO reservation (created_date, last_modified_date, lecture_id, member_id, status, reservation_id) VALUES (now(), now(), 3, 12, 'COMPLETE', 42);
INSERT INTO reservation (created_date, last_modified_date, lecture_id, member_id, status, reservation_id) VALUES (now(), now(), 3, 13, 'COMPLETE', 43);